version: '3.8'
services:
  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 budidayaplus.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1